### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by Dmitry170** [Dynatrace/Dynatrace-hybris-eCommerce-Fastpack#3]
Hi,
I don't understand what I am doing wrong:
1) I generated a token
![image](https://user-images.githubusercontent.com/47598140/52714420-da01af00-2faa-11e9-9353-26a62bbe4b12.png)
2) Made sure that Python version 3, made sure that all the modules are there
Python 3.4.5 (default, May 29 2017, 15:17:55)
   [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
   Type "help", "copyright", "credits" or "license" for more information.
   >>> import datetime
   >>> import getpass
   >>> import json
   >>> import logging
   >>> import requests
   >>> import time
   >>> import sys
3) Launched the script indicating the key above and environment ID
Enter your tenant API token for the Config API:
Enter your Tenant URL (example: foo.live.dynatrace.com): slx367.dynatrace-managed.com/e/[id-environment]
4) And I see
Validating API access on the tenant
********************************************
 ******************* FAIL *******************
 ********************************************
 Status code 403 returned. Most likely cause is incorrect permissions on the API token.
 Please make sure this token has the following privileges:
 - Read configuration
 - Write configuration
 - Capture request data

**Comment by ingohackl** [comment]
Your access setup for token must look like this:
![image](https://user-images.githubusercontent.com/10072044/53171593-7fd49f80-35e3-11e9-9a41-3b6779a5b93b.png)

Interesting that you don't have the options for "Read Configuration", "Write Configuration" not available.

**Comment by Dmitry170** [comment]
we found our problem. We have version 1.160.135.20190204 and we do not have this functionality.

**Comment by Dynatrace-BrianWilson** [comment]
There have been some changes in the API recently, and a couple of more on the way. I think by v165, they'll all be in place. I'll be updating the fastpack again then.  
One change is that the path to the custom services and request attributes APIs will change. There is a yet unknown change to request naming rules. They will be missing for a few builds.  In the meantime, you can apply the request naming rules manually.
